name: Run Specified Version Test

on:
  workflow_call:
    inputs:
      nats_jetstream_version:
        description: 'NATS JetStream Version'
        required: true
        type: string
      gravity_dispatcher_version:
        description: 'Gravity Dispatcher Version'
        required: true
        type: string
      atomic_version:
        description: 'Atomic Version'
        required: true
        type: string
      gravity_adapter_mssql_version:
        description: 'Gravity Adapter Version'
        required: true
        type: string
      gravity_sdk_version:
        description: 'Gravity SDK Version'
        required: true
        type: string
    secrets:
      RUN_TOKEN:
        description: 'Run Token'
        required: true
      DOCKERHUB_USERNAME:
        description: 'Dockerhub Username'
        required: true
      DOCKERHUB_TOKEN:
        description: 'Dockerhub Token'
        required: true
      GHCR_USERNAME:
        description: 'GHCR Username'
        required: true

  workflow_dispatch:
    inputs:
      nats_jetstream_version:
        description: 'NATS JetStream Version'
        required: true
        default: 'v1.3.21-20250201'
      gravity_dispatcher_version:
        description: 'Gravity Dispatcher Version'
        required: true
        default: 'v0.0.31-20250220'
      atomic_version:
        description: 'Atomic Version'
        required: true
        default: 'v1.0.0-20250301-ubi'
      gravity_adapter_mssql_version:
        description: 'Gravity Adapter Version'
        required: true
        default: 'v3.0.15-20250201'
      gravity_sdk_version:
        description: 'Gravity SDK Version'
        required: true
        default: 'v2.0.7'

permissions:
  contents: write

jobs:
  Run-tests:
    environment: Specified_Version_Test
    runs-on: 
      - self-hosted
      - tests

    steps:
      - name: Set Variable
        run: |
          echo "TIME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout cli-test Repository # TODO: 改main branch
        uses: actions/checkout@v4
        with:
          repository: BrobridgeOrg/gravity-cli-tests
          token: ${{ secrets.RUN_TOKEN }}
          path: test_code/gravity-cli-tests
          ref: GN-206_specified_version_test

      - name: Checkout E2E-test Repository # TODO: 改main branch
        uses: actions/checkout@v4
        with:
          repository: BrobridgeOrg/End-to-End-test
          token: ${{ secrets.RUN_TOKEN }}
          path: test_code/e2e-tests
          ref: GN-206_specified_version_test
          
      - uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: "latest"

      - name: Docker Login
        run: | 
          docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password "${{ secrets.DOCKERHUB_TOKEN }}"
          docker login ghcr.io --username "${{ secrets.GHCR_USERNAME }}" --password "${{ secrets.RUN_TOKEN }}"
      - run: earthly bootstrap

      - name: Run Test Scripts
        run: |
          echo "Running tests"
          chmod +x scripts/run_all.sh
          scripts/run_all.sh ${{inputs.nats_jetstream_version}} ${{inputs.gravity_dispatcher_version}} ${{inputs.atomic_version}} ${{inputs.gravity_adapter_mssql_version}} ${{inputs.gravity_sdk_version}}

      - name: Create Test Report
        run: |
          chmod +x scripts/create_test_report.sh
          scripts/create_test_report.sh ${{inputs.nats_jetstream_version}} ${{inputs.gravity_dispatcher_version}} ${{inputs.atomic_version}} ${{inputs.gravity_adapter_mssql_version}} ${{inputs.gravity_sdk_version}} $TIME

      - name: Create Config File
        run: |
          chmod +x scripts/create_config.sh
          scripts/create_config.sh ${{inputs.nats_jetstream_version}} ${{inputs.gravity_dispatcher_version}} ${{inputs.atomic_version}} ${{inputs.gravity_adapter_mssql_version}} ${{inputs.gravity_sdk_version}} $TIME

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git add test_reports/*
          git commit -m "Update test_summary [skip ci]" || echo "No changes to commit"
          git push origin main
