name: Run Specified Version Test

on:
  workflow_dispatch:
    inputs:
      nats_jetstream_version:
        description: 'NATS JetStream Version'
        required: true
        default: 'v0.0.31-20250220'
      gravity_dispatcher_version:
        description: 'Gravity Dispatcher Version'
        required: true
        default: 'v1.3.21-20250117'
      gravity_sdk_version:
        description: 'Gravity SDK Version'
        required: true
        default: 'v2.0.7'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout cli-test Repository # TODO: 改main branch
        uses: actions/checkout@v4
        with:
          repository: BrobridgeOrg/gravity-cli-tests
          token: ${{ secrets.RUN_TOKEN }}
          path: test_code/gravity-cli-tests
          ref: GN-206_specified_version_test

      - name: Run Test Scripts
        run: |
          echo "Running tests"
          ls
          echo "---"
          ls test_code/gravity-cli-tests
          echo "---"
          ls scripts/
          chmod +x ./scripts/run-all.sh
          ./scripts/run-all.sh ${{github.event.inputs.nats_jetstream_version}} ${{github.event.inputs.gravity_dispatcher_version}} ${{github.event.inputs.gravity_sdk_version}}

      - name: Create Test Report
        run: |
          echo "Generating test report"
          chmod +x ./scripts/generate-report.sh
          ./scripts/create_test_report.sh

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git add ./test_report_*
          git commit -m "Update test_summary [skip ci]" || echo "No changes to commit"
          git push origin main
