name: Run Versioning Test

on:
  workflow_dispatch:
    inputs: 
      version_number:
        description: 'Version Number'
        required: true
        default: 'v1.0'

permissions:
  contents: write

jobs:
  Get-service-versions:
    environment: Specified_Version_Test
    runs-on: 
      - self-hosted
      - tests
    outputs:
      nats_jetstream_version: ${{ steps.get_each_version_from_config_file.outputs.nats_jetstream_version }}
      gravity_dispatcher_version: ${{ steps.get_each_version_from_config_file.outputs.gravity_dispatcher_version }}
      atomic_version:  ${{ steps.get_each_version_from_config_file.outputs.atomic_version }}
      gravity_adapter_mssql_version:  ${{ steps.get_each_version_from_config_file.outputs.gravity_adapter_mssql_version }}
      gravity_sdk_version:  ${{ steps.get_each_version_from_config_file.outputs.gravity_sdk_version }}
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get_each_version_from_config_file
        id: get_each_version_from_config_file
        run: |
          chmod +x scripts/get_version.sh
          OUTPUT=$(scripts/get_version.sh ${{github.event.inputs.version_number}})
          echo $OUTPUT >> $GITHUB_OUTPUT

      - name: Check output variables
        run: |
          echo nats_jetstream_version: ${{ steps.get_each_version_from_config_file.outputs.nats_jetstream_version }}
          echo gravity_dispatcher_version: ${{ steps.get_each_version_from_config_file.outputs.gravity_dispatcher_version }}
          echo atomic_version:  ${{ steps.get_each_version_from_config_file.outputs.atomic_version }}
          echo gravity_adapter_mssql_version:  ${{ steps.get_each_version_from_config_file.outputs.gravity_adapter_mssql_version }}
          echo gravity_sdk_version:  ${{ steps.get_each_version_from_config_file.outputs.gravity_sdk_version }}

  Trigger-main-workflow:
    needs: Get-service-versions
    uses: ./.github/workflows/main.yml
    with:
      nats_jetstream_version: ${{needs.Get-service-versions.outputs.nats_jetstream_version}}
      gravity_dispatcher_version: ${{needs.Get-service-versions.outputs.gravity_dispatcher_version}}
      atomic_version: ${{needs.Get-service-versions.outputs.atomic_version}}
      gravity_adapter_mssql_version: ${{needs.Get-service-versions.outputs.gravity_adapter_mssql_version}}
      gravity_sdk_version: ${{needs.Get-service-versions.outputs.gravity_sdk_version}}
    secrets:
      RUN_TOKEN: ${{secrets.RUN_TOKEN}}
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
      GHCR_USERNAME: ${{secrets.GHCR_USERNAME}}