name: Run Versioning Test

on:
  workflow_dispatch:
    inputs: 
      version_number:
        description: 'Version Number'
        required: true
        default: 'v1.0'

permissions:
  contents: write

jobs:
  Get-service-versions:
    environment: Specified_Version_Test
    runs-on: 
      - self-hosted
      - tests
    outputs:
      nats_jetstream_version: ${{ steps.Get_each_version_from_config_file.outputs.nats_jetstream_version }}
      gravity_dispatcher_version: ${{ steps.Get_each_version_from_config_file.outputs.gravity_dispatcher_version }}
      atomic_version:  ${{ steps.Get_each_version_from_config_file.outputs.atomic_version }}
      gravity_adapter_mssql_version:  ${{ steps.Get_each_version_from_config_file.outputs.gravity_adapter_mssql_version }}
      gravity_sdk_version:  ${{ steps.Get_each_version_from_config_file.outputs.gravity_sdk_version }}
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get_each_version_from_config_file
        run: |
          CONFIG_FILE=configs/${{github.event.inputs.version_number}}.json
          if [ ! -f "$CONFIG_FILE" ]; then
              echo "Error: Can't find $CONFIG_FILE"
              exit 1
          fi
          
          GRAVITY_SDK=$(jq -r '.package["gravity-sdk"]' "$CONFIG_FILE")
          NATS_JETSTREAM=$(jq -r '.gravity["nats-jetstream"]' "$CONFIG_FILE")
          GRAVITY_DISPATCHER=$(jq -r '.gravity["gravity-dispatcher"]' "$CONFIG_FILE")
          ATOMIC=$(jq -r '.gravity["atomic"]' "$CONFIG_FILE")
          GRAVITY_ADAPTER_MSSQL=$(jq -r '.gravity["gravity_adapter_mssql"]' "$CONFIG_FILE")

          echo "gravity_sdk_version=$GRAVITY_SDK" >> $GITHUB_OUTPUT
          echo "nats_jetstream_version=$NATS_JETSTREAM" >> $GITHUB_OUTPUT
          echo "gravity_dispatcher_version=$GRAVITY_DISPATCHER" >> $GITHUB_OUTPUT
          echo "atomic_version=$ATOMIC" >> $GITHUB_OUTPUT
          echo "gravity_adapter_mssql_version=$GRAVITY_ADAPTER_MSSQL" >> $GITHUB_OUTPUT

      - name: Check out
        run: |
          echo nats_jetstream_version: ${{ steps.Get_each_version_from_config_file.outputs.nats_jetstream_version }}
          echo gravity_dispatcher_version: ${{ steps.Get_each_version_from_config_file.outputs.gravity_dispatcher_version }}
          echo atomic_version:  ${{ steps.Get_each_version_from_config_file.outputs.atomic_version }}
          echo gravity_adapter_mssql_version:  ${{ steps.Get_each_version_from_config_file.outputs.gravity_adapter_mssql_version }}
          echo gravity_sdk_version:  ${{ steps.Get_each_version_from_config_file.outputs.gravity_sdk_version }}

  Trigger-main-workflow:
    needs: Get-service-versions
    uses: ./.github/workflows/main.yml
    with:
      nats_jetstream_version: ${{needs.Get-service-versions.outputs.nats_jetstream_version}}
      gravity_dispatcher_version: ${{needs.Get-service-versions.outputs.gravity_dispatcher_version}}
      atomic_version: ${{needs.Get-service-versions.outputs.atomic_version}}
      gravity_adapter_mssql_version: ${{needs.Get-service-versions.outputs.gravity_adapter_mssql_version}}
      gravity_sdk_version: ${{needs.Get-service-versions.outputs.gravity_sdk_version}}
    secrets:
      RUN_TOKEN: ${{secrets.RUN_TOKEN}}
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
      GHCR_USERNAME: ${{secrets.GHCR_USERNAME}}