name: Run Versioning Test

on:
  workflow_dispatch:
    inputs: 
      version_number:
        description: 'Version Number'
        required: true
        default: 'v1.0'

permissions:
  contents: write

jobs:
  Run-tests:
    environment: Specified_Version_Test
    runs-on: 
      - self-hosted
      - tests

    steps: 
      - name: get_each_version_from_config_file
        run: |
          chmod +x scripts/get_version.sh
          OUTPUT = $(scripts/get_version.sh ${{github.event.inputs.version_number}})
          echo "$OUTPUT"

      - name: Trigger Main Workflow
        uses: ./.github/workflows/main.yml
        with:
          nats_jetstream_version: ${{ steps.get_each_version_from_config_file.outputs.nats_jetstream_version }}
          gravity_dispatcher_version: ${{ steps.get_each_version_from_config_file.outputs.gravity_dispatcher_version }}
          atomic_version: ${{ steps.get_each_version_from_config_file.outputs.atomic_version }}
          gravity_adapter_mssql_version: ${{ steps.get_each_version_from_config_file.outputs.gravity_adapter_mssql_version }}
          gravity_sdk_version: ${{ steps.get_each_version_from_config_file.outputs.gravity_sdk_version }}
          