name: Run Versioning Test

on:
  workflow_dispatch:
    inputs: 
      version_number:
        description: 'Version Number'
        required: true
        default: 'v1.0'

permissions:
  contents: write

jobs:
  Get-service-versions:
    environment: Specified_Version_Test
    runs-on: 
      - self-hosted
      - tests
    outputs:
      nats_jetstream_version: ${{ steps.get_version.outputs.nats_jetstream_version }}
      gravity_dispatcher_version: ${{ steps.get_version.outputs.gravity_dispatcher_version }}
      atomic_version: ${{ steps.get_version.outputs.atomic_version }}
      gravity_adapter_mssql_version: ${{ steps.get_version.outputs.gravity_adapter_mssql_version }}
      gravity_sdk_version: ${{ steps.get_version.outputs.gravity_sdk_version }}
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: get_each_version_from_config_file
        run: |
          echo "gravity_sdk_version=v2.0.7" >> $GITHUB_OUTPUT
          echo "nats_jetstream_version=v1.3.21-20250201" >> $GITHUB_OUTPUT
          echo "gravity_dispatcher_version=v0.0.31-20250220" >> $GITHUB_OUTPUT
          echo "atomic_version=v1.0.0-20250301-ubi" >> $GITHUB_OUTPUT
          echo "gravity_adapter_mssql_version=v3.0.15-20250201" >> $GITHUB_OUTPUT

  Trigger-main-workflow:
    needs: Get-service-versions
    uses: ./.github/workflows/main.yml
    with:
      nats_jetstream_version: needs.Get-service-versions.outputs.nats_jetstream_version
      gravity_dispatcher_version: needs.Get-service-versions.outputs.gravity_dispatcher_version
      atomic_version: needs.Get-service-versions.outputs.atomic_version
      gravity_adapter_mssql_version: needs.Get-service-versions.outputs.gravity_adapter_mssql_version
      gravity_sdk_version: needs.Get-service-versions.outputs.gravity_sdk_version
    secrets:
      RUN_TOKEN: ${{secrets.RUN_TOKEN}}
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
      GHCR_USERNAME: ${{secrets.GHCR_USERNAME}}