name: Run Versioning Test

on:
  workflow_dispatch:
    inputs: 
      version_number:
        description: 'Version Number'
        required: true
        default: 'v1.0'

permissions:
  contents: write

jobs:
  Get-service-versions:
    environment: Specified_Version_Test
    runs-on: 
      - self-hosted
      - tests

    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: get_each_version_from_config_file
        run: |
          chmod +x scripts/get_version.sh
          OUTPUT=$(scripts/get_version.sh ${{github.event.inputs.version_number}})
          echo "$OUTPUT" >> $GITHUB_ENV

  Trigger Main Workflow:
    uses: ./.github/workflows/main.yml
    with:
      nats_jetstream_version: $nats_jetstream_version
      gravity_dispatcher_version: $gravity_dispatcher_version
      atomic_version: $atomic_version
      gravity_adapter_mssql_version: $gravity_adapter_mssql_version
      gravity_sdk_version: $gravity_sdk_version
          